#!/usr/bin/env bash
# Display a list of currently running processes with hierarchy
# Uses command options, 'a' to list all processes
# 'a' to display all processes
# 'u' to show process for all users
# 'x' to include those without TTY
# 'f' to display user-oriented output
ps auxf
