#!/usr/bin/env bash
# Function to handle SIGTERM SIGQUIT signals

cleanup() {
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit 0
}

# Trap signals and associate them with the cleanup function
trap 'cleanup' SIGQUIT SIGTERM

# Create PID file
echo $$ > /var/run/myscript.pid

# Function to handle SIGINT signal
handle_sigint()
{
    echo "Y U no love me?!"
}

# Trap SIGINT signal and associate it with the handle_sigint function
trap 'handle_sigint' SIGINT

# Main loop to display message indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 2
done

