#!/usr/bin/env bash
# The script displays the content of the file /etc/passwd

# Read line by line until the end of the file is reached

while IFS=':' read -r username _ uid gid info home shell; do
	# Extracting the password field for the user
	password=$(getent passwd "$username" | cut -d: -f2)

	#Displaying the formatted information
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"

done < "/etc/passwd"
