#!/usr/bin/env bash
# The script displays the content of the file /etc/passwd

# Read line by line until the end of the file is reached

gid=""

while IFS=':' read -r username _ _ _ info home shell; do
	group=$(getent group "$gid" | cut -d: -f1)

	# Extracting the password field for the user
	password=$(getent passwd "$username" | cut -d: -f2)

	#Displaying the formatted information
    echo "The user $username is part of the $group gang, lives in $home and rides $shell. User ID's place is protected by the passcode $password, more info about the user here: $info"

done < "/etc/passwd"
