#!/usr/bin/env bash
# This script configures an Ubuntu server according to the specified requirements.

# Requirement: localhost resolves to 127.0.0.2
# Requirement: facebook.com resolves to 8.8.8.8

# Create a backup of the hosts file
cp /etc/hosts ~/hosts.new

# Modify the backup file to change localhost resolution
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new

# Insert the resolution for facebook.com into the backup file
sed -i '2i8.8.8.8 facebook.com' ~/hosts.new

# Overwrite the original hosts file with the modified backup
cp -f ~/hosts.new /etc/hosts
