#!/usr/bin/env bash
# This script connects to a server using SSH with a specified private key and user ubuntu.

# Connect to the server using ssh with the private key ~/.ssh/school and user ubuntu
ssh -i ~/.ssh/school ubuntu@100.25.188.160
