#!/usr/bin/env bash
# This script creates an RSA key pair named 'school' with 4096 bits and protects it with the passphrase 'betty'.

# Define the file path for the key pair
KEY_PATH="$HOME/.ssh/school"

# Define the passphrase
PASSPHRASE="betty"

# Create the RSA key pair with 4096 bits and the specified passphrase
ssh-keygen -t rsa -b 4096 -f "$KEY_PATH" -N "$PASSPHRASE"
